### ISSUE TITLE
🚧Change how release note validation works

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#103]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, validating release notes for GitHub action releases validates the contents of the release notes.  This is not ideal because it was decided not to use milestones for GitHub actions due to how infrequent development and changes occur. This means it is just not worth the effort of painting milestones.

Because there is no milestone, there is no container for the issues and pull requests to be able to use for validating what is inside the release notes.

However, the release notes still need to be verified of its existence.  Refactor the `validate_release_notes` job to use Powershell to check that the notes exist, instead of using the reusable workflow.

### Acceptance Criteria

**This issue is finished when:**
- [x] Refactor the release notes validation job in the _**dotnet-action-release.yml**_ release workflow

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
