### ISSUE TITLE
🚧Update action version in workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#11]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the following actions in the YML files to latest versions:

- build-csharp-project.yml
    ```diff
        - name: Setup .NET SDK
    -      uses: actions/setup-dotnet@v1
    +      uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ inputs.net-sdk-version }}
    ```
- run-csharp-tests.yml
    ```diff
    -    - uses: actions/setup-dotnet@v1
    +    - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ inputs.net-sdk-version }}
    ```

### Acceptance Criteria

- [x] The **_build-csharp-project.yml_** workflow updated
- [x] The _**run-csharp-tests.yml**_ workflow updated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
