### ISSUE TITLE
🚧Goto the github actions page and delete all workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#112]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go To all of the actions for the workflow _**new-test-file.yml**_.

These were all used for testing during the implementation of the issue:
- #59 

<img width="307" alt="image" src="https://github.com/KinsonDigital/Infrastructure/assets/85414302/4e5fa0f2-85c7-4262-a44c-981aec871a7f">

### Acceptance Criteria

**This issue is finished when:**
- [x] All workflows deleted

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
