### ISSUE TITLE
🚧Add ability to autoupdate csproj version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#113]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to automatically update the version data in csproj files when running the prepare release process.

**Things needed:**
1. Automatically update the version data in the csproj
    - File should be chosen by project name being input into the system
    - The `<Version/>` and `<FileVersion/>` tags updated
    - If either tag does not exist, throw an error and fail

**Additional:**
1. Add the ability to check if the incoming org exists in the `PrepareReleaseRunner` class
    > **Note** This should be a reusable function in the `ScriptRunner` class
2. Add the ability to check if the incoming org exists in the `PrepareReleaseRunner` class
    > **Note** This should be a reusable function in the `ScriptRunner` class
3. Add/refactor code to make sure that a token is always present.  
    > **Note** Make sure that the 2 types of tokens are valid.
    > Fine Grained Token: Starts with `github_pat_` and the length is exactly 94
    > Token (Classic): Starts with `ghp_` and the length is exactly 41.
4. Lint status check added for linting for quality
5. Create a runner for send release tweet script

> **Note** This is going to force the org and repo clients to be created in the `ScriptRunner` class.  In effect, this will also force every single runner to have a token.  This is ok though since it is just better to always use a token even if it is not really technically needed.

### Acceptance Criteria

**This issue is finished when:**
- [x] Version data auto-updated in the csproj file
- [x] Token verification added
    - [x] Fine-grained verification added
    - [x] Token classic verification added
- [x] Lint status check created to add linting for code quality
- [x] Create runner for send release tweet script
- [x] All references to the org secret `CICD_REST_API` updated to `CICD_TOKEN`
- [x] All reusable workflow refs updated to the latest version

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
