### ISSUE TITLE
🚧Improve readme transpiling process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#118]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the readme transpiling process by detecting any markdown images that use the special GitHub syntax for light vs dark mode.

The reason for dark vs light mode is that some images need to have both types for the different themes that can be used in GitHub.
Examples of this are the **CASL** and **Carbonate** projects.  The main project readme files contain both modes.

The reason for needing to detect this is that nuget.org does not utilize this special syntax.  Without mutating the README file before the deployment of a NuGet package, both logo images will show up.  The nuget.org website does not have a dark and light mode.  It only has a light mode.

**What needs to be done?**

We need to be able to detect if images contain the special syntax for light and dark modes, this way we can remove one and leave the other behind. This way the dark mode version does not make it into the Nuget package during deployment.

**Details:**
1. Need to detect light mode syntax
2. Need to detect dark mode syntax
3. Need to altogether remove the dark mode image, but only if another exact copy exists for a light mode version
    > **Note** This will require detection of the image URLs themselves containing a file name that ends with `-light-mode` or `-dark-mode`.  If the rest of the file names minus the `-light-mode` or `-dark-mode` text for both files are the same, then they are light-mode and dark-mode versions of each other.  If this requirement is not met, then no markdown image links will be removed.
    > Example: 
    > - File 1: https://raw.githubusercontent.com/Owner/MyRepo/main/v1.2.3/images/my-logo-light-mode.png
    > - File 2: https://raw.githubusercontent.com/Owner/MyRepo/main/v1.2.3/images/my-logo-dark-mode.png
    > In the 2 files, if you were to remove the `-light-mode` and/or `-dark-mode` section from the end of the file, what would be left of the files would be the same with a value of `my-logo`.  This means the intent of both files expressed in the file name means they are the same logo but one is for light and one is for dark.  The values `#gh-light-mode-only` and `#gh-dark-mode-only` are at the very end of the URL links.  They cannot be shown here as a full URL because you would not be able to see one of them depending on what theme you are using while viewing this issue.
    > Here is what it would look like without the full URL.
    > - `my-logo-dark-mode.png#gh-dark-mode-only`    
4. Detection of the light or dark mode markdown images follow the rules below:
    - The text `-light-mode` and `#gh-light-mode-only` need to both exist in the URL for it to be considered a valid light-mode image.
    - The text `-dark-mode` and `#gh-dark-mode-only` need to both exist in the URL for it to be considered a valid dark-mode image.
    - The removal will only be the dark mode version
    - The removal will only occur if the dark mode version has an equivalent light mode version to be left behind after the dark mode version is deleted.

### Acceptance Criteria

**This issue is finished when:**
- [x] Dark vs light mode processing added to the transpilation process of the readme file

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
