### ISSUE TITLE
🚧Fix sync issue with pr template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#119]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with the pr template not being found when syncing the issue to the pull request.

This is occurring because the location where the template is being looked at is incorrect.  This works fine in infrastructure but when running the syncing system in other projects that don't contain the template, this issue occurs.

This is because the pull request head branch is being used when checking if the file exists when the branch being used should be the branch of the repo where the template exists.  Currently, the template exists in the **Infrastructure** repository but the script is using the **Infrastructure** repo with a head branch from the pull request where the syncing system is being executed.

This will require a new repository variable to be created with the name **PR_SYNC_TEMPLATE_BRANCH_NAME**.  This will hold the branch where the template exists in the repository.  

### Acceptance Criteria

**This issue is finished when:**
- [x] Sync location bug fixed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
