### ISSUE TITLE
🚧Fix initial sync issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#121]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with the initial sync not working.

This is because the pull request body is being checked if the syncing process is enabled/disabled during the initial sync process.   This does not work though because the pr body does not contain any data so it will always return disabled and never sync.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Initial sync issue fixed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
