### ISSUE TITLE
🚧Improve csharp proj file resolution

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#123]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the resolving of csharp project files by creating a deno script that will be used to perform the resolving/searching for the project file.

Currently, the workflow _**resolve-csharp-proj-file.yml**_ uses PowerShell to do this.  This workflow must be updated to execute the script to perform the work.

This script needs to recursively search as deep as possible until it finds the **FIRST OCCURRENCE** of a project file name that matches the incoming `project-name` workflow input value.

The script will also need to save the fully qualified file path to the GitHub output file.  
    > **Note** Here is how it is done in PowerShell: `"project-file-path=projFilePath" >> $env:GITHUB_OUTPUT;`

**The script should also do the following:**
1. Make sure to print a notice message that the file path has been saved to the output file
    - The file path should be printed
    - The output file path should be printed
2. Throw and error/fail if no project file was found
    - Print the error to the console
3. The script will take the following args:
    - project name
    - token
4. Create a runner for this script
5. Create a script file to execute the runner

**The workflow should do the following:**
    - Install deno as a step
    - Take a `base-path` optional workflow input just as before.
    - If the `base-path` workflow input is empty/null, use the `$eng:GITHUB_WORKSPACE` env var

### Acceptance Criteria

**This issue is finished when:**
- [ ] Resolve project file path script created
    - [ ] script file created
    - [ ] runner created that is executed by the script file
    - [ ] Notice message is printed about the file path found
      - [ ] The file path should be printed
      - [ ] The output file path should be printed
    - [ ] Error/fail message printed and workflow fails if no project file was found
    - [ ] The script takes the following args:
      - [ ] project name
      - [ ] token
- [ ] Issue created for **BranchValidator** project to re-enable disabled job in the _**build-status-check.yml**_ workflow.

- [ ] Workflow updated
    - deno installed as a step (v1.35.x)
    - Take a `base-path` optional workflow input just as before.
    - If the `base-path` workflow input is empty/null, use the `$eng:GITHUB_WORKSPACE` env var

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
