### ISSUE TITLE
🚧Fix branch creation issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#124]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with creating branches during the prepare release process.
This occurs when trying to create the _**prev-release**_ branch when running the _**prepare-release.ts**_ script.

### Acceptance Criteria

**This issue is finished when:**
- [x] Branch creation issue fixed
- [x] All scripts updated to the latest version
- [x] CICD scripts version repository var value updated
- [ ] Issues created for other projects to update to latest infrastructure version

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
