### ISSUE TITLE
🚧Exclude issues from release notes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#126]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Exclude open issues in the release notes when running the **_prepare-release.ts_** script.

Also, print to the console all of the issues that are currently in the open status.
  > **Note** Make sure to exclude any issues that have a label from the _**ignore labels list**_ that comes from the _**IGNORE_LABELS**_ org/repo variable.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Open issues excluded from the release notes
- [ ] Opened issues are printed to the console in a group
    - [ ] Issues that are in the **closed** or **open** state with a label from the ignore list are not printed to this log message
- [ ] A warning message using the `::warning::` workflow command is printed to the console that there are some opened issues.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue Closed

**Reason:**
This has been replaced by the new prepare release process.
