### ISSUE TITLE
🚧Fix pathing issue in release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#127]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the _**dotnet-lib-release.yml**_ reusable workflow, fix a pathing issue in the `perform_release` job and `Creating ${{ inputs.release-type }} GitHub Release` step where the `body_path` and `files` for the `softprops/action-gh-release@v1` GitHub action workflow input values are incorrect.

Also, check if this is the issue as well for the _**dotnet-action-release.yml**_ reusable workflow as well.

### Acceptance Criteria

**This issue is finished when:**
- [ ] dotnet lib release workflow updated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
