### ISSUE TITLE
🚧Create script version status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#132]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a status check that uses internal deno scripts to verify if the reusable workflow versions have not been updated.

This can be done by comparing the latest tag version currently in existence to the tag versions of each reusable workflow.  If any of the workflows need to be updated, then the status check should fail.

All workflows that need to be updated should be printed as a group to the console as well as an error using the `::error::` workflow command.  The scripts will reside in the project itself and also the workflow will execute those local scripts.

### Acceptance Criteria

**This issue is finished when:**
- [x] Deno script versions status check created
    - [x] Checks if a reusable workflow version has NOT been updated
    - [x] All reusable workflows with a version to be updated are printed as error
- [x] Repository variable `CICD_SCRIPTS_VERSION` value checked and logged if it has not been updated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
