### ISSUE TITLE
🚧Fix send release tweet bug

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#135]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When performing a release for **Carbonate v1.0.0-preview.15**, the _**Send Twitter Announcement**_ step in the `perform_release` job failed in the _**dotnet-lib-release.yml**_ file.

It is unknown as to why the failure occurred.  The assumption is that the regex might be incorrect.

To review the error and inputs provided, refer to the [failed workflow](https://github.com/KinsonDigital/Carbonate/actions/runs/5717949189/job/15492801844).

Image Of Error:
<img width="624" alt="image" src="https://github.com/KinsonDigital/Infrastructure/assets/85414302/05cca4b8-c6a5-46b8-9e50-64af9c8d5534">

### Acceptance Criteria

**This issue is finished when:**
- [ ] Add item here . . .

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
