### ISSUE TITLE
🚧Fix initial PR sync issue

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Infrastructure#138]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix and issue with the initial PR sync process.  Currently the script is checking for 5 arguments, but 6 arguments are being passed in, causing a failure. 

The issue is in the `validateArgs()` function in the `SyncPRToIssueRunner.ts` class.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Issue fixed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
