### ISSUE TITLE
🚧Auto Proj Testing

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#14]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

asdf

### Acceptance Criteria

**This issue is finished when:**
- [ ] Add item here . . .

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
