### ISSUE TITLE
🚧Add release notes content option

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#140]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to the generate release notes system which is utilized in the _**prepare-release.yml**_ workflow.

Add a new repository/org variable that is boolean and if `true`, the release notes will generate the content from the milestone.  If `false`, then only the file will be generated with no issues added to it.

The default value will be `false `and if the repo variable does not exist, then it is `false`.  If `false`, then the entire release notes file with all of the sections will be generated but will not have any issues added to it.  This will give the user everything they need to manually add the items.

The name of the repo variable should be `ADD_ITEMS_FROM_MILESTONE`.

### **Reason:**
The reason for this feature is that GitHub actions do not use milestones so there are no milestones to pull issues and pull requests from.  This causes the process to fail.  Instead, Github action release notes are manually written.

### Acceptance Criteria

**This issue is finished when:**
- [x] generate release notes system adjusted to use or not use milestone items as content
    - [x] A repo variable with the name `ADD_ITEMS_FROM_MILESTONE` added
    - [x] Milestone items are not added to the notes if the repo var is missing or set to `false`.
    - [x] When the variable does not exist, a notice is printed that the var is optional and is missing
    - [x] When the variable is missing or is `false`, a notice is printed that milestone items were not added
    - [x] Release notes with all sections generated with no milestone items if the repo variable is missing or `false`
- [x] Go through all repos that require the notes from the milestone and add a repo var to override the org repo.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
