### ISSUE TITLE
🚧Fix various issues with github action release process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#141]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

There are various issues with the release process for GitHub actions.  

Fix the following:
1. Simple spelling issue
![image](https://github.com/KinsonDigital/Infrastructure/assets/85414302/fa9b4b73-c081-435c-b80d-2001a635635a)
2. `Validate Release Notes Exists` job is failing
3. `Validate Tag` job is failing.  Says it must have 4 args but only has 3 args
4. `Validate GitHub Release` job is failing.  Says it must have 3 args but only has 2 args
5. When creating the GitHub release, too many letter `v` characters are being added to the title
![image](https://github.com/KinsonDigital/Infrastructure/assets/85414302/cd592dfb-84c7-48e2-bdf7-fc8ed19ef608)
6. GitHub release is not auto setup to the marketplace
7. The `Perform Production Release` job passed when it should not of.  The other 3 jobs failed so this job should have failed.

### Acceptance Criteria

**This issue is finished when:**
There are various issues with the release process for GitHub actions.  

Fix the following:
- [x] Simple issue fixed
- [x] `Validate Release Notes Exists` job fixed
- [x] `Validate Tag` job arg processing fixed
- [x] `Validate GitHub Release` job arg processing fixed
- [x] Extra  `v` character removed from GitHub release title
- [x] `Perform Production Release` dependencies adjusted

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
