### ISSUE TITLE
🚧Implement various improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#144]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Implement the following improvements

1. Update the **_dotnet-lib-release.yml_** workflow to execute the **Publish Nuget Package** step last but still right the Twitter announcement.
2. Rename the **Send Twitter Announcement** step name to **Send X Announcement** in the `preform_release` job.
3. Update the Twitter logo link and text in the PR template generated by the `prepare-release.yml` workflow
4. In the `dotnet-lib-release.yml` workflow `print_validate_workflow` job, validate the workflow input named `relative-release-notes-dir-path` to see if the directory path exists.
    > **Note** Make sure to add a checkout step before the `Validate Workflow Inputs` step
    > This will check that the directory path exists
5. Rename the `PREP_PROJ_RELATIVE_FILE_PATH` repo file to `PREP_RELATIVE_CSHARP_PROJ_FILE_PATH`
    > **Note** Make sure to update the name of the repo variable for the project and add this to the rest of the projects
    > **Warning** Do not remove the old variable from the old projects yet!!  They depend on this variable still.
    > This is a https://github.com/KinsonDigital/Infrastructure/labels/%F0%9F%A7%A8breaking%20changes

### Acceptance Criteria

**This issue is finished when:**
- [ ] The **Publish Nuget Package** step in the **_dotnet-lib-release.yml_** workflow has been moved
- [ ] The **Send Twitter Announcement** step has been renamed
- [ ] The Twitter logo link and text updated in the prepare release templates
- [ ] The `relative-release-notes-dir-path` workflow input dir value in workflow `print_validate_workflow` job has been validated.
    - [ ] Checkout repo step added before the `Validate Workflow Inputs` step
- [ ] The `PREP_PROJ_RELATIVE_FILE_PATH` repo variable renamed to `PREP_RELATIVE_CSHARP_PROJ_FILE_PATH` in the prepare release script
    - [ ] The repository variable is added to all projects
        > **Warning** Do not remove the old variable from the old projects yet!!  They depend on this variable still.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
