### ISSUE TITLE
🚧Create docusaurus reusable release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#154]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a reusable workflow that can be used for performing docusaurus releases.  Use the _**prod-release.yml**_ workflow in the _**VelaptorDocs**_ project as a guide.

Also, create a function in the `WorkflowRunClient` class that executes a workflow via file name.

> **Note**
> Some steps are specific to the _**VelaptorDocs**_ project and should not be carried over.  Only bring over what is needed and extract any values to workflow inputs for other workflows to consume properly.

**Other:**
1. Delete the **_project item issue_**  template file
2. Update the _**bug**_ template file by adding projects and updating the os choice to a browser dropdown

### Acceptance Criteria

**This issue is finished when:**
- [x] Docusaurus release workflow created
- [x] Project item issue template deleted
- [x] Bug issue template updated
- [x] Workflow Client Updates
    - [x] New function added to execute workflows
    - [x] Workflow file renamed to `WorkflowClient.ts`

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
