### ISSUE TITLE
🚧Fix arg processing bug

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#156]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug with the transpile release process.  It seems that the mutation of the arguments is removing the GitHub token which is changing the count of the args coming in.  This is then being caught by the validation process and the script fails.

### Acceptance Criteria

- [ ] Arg processing bug fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
