### ISSUE TITLE
🚧Various improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#158]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

1. Create a new reusable workflow for the _**sync-issue-to-pr.yml**_ workflows used across the org projects
2. Fix an issue when running the _**sync-issue-to-pr.ts**_ via the `[run-sync]` comment command under a user that does not belong to the KinsonDigital organization. The issue is that the script will work fine in regard to preventing the sync processing from being triggered, but it does not fail the workflow.
3. Make a simple adjustment to the console warning message when an issue number cannot be found
![image](https://github.com/KinsonDigital/Infrastructure/assets/85414302/62051ed6-2926-49d6-a11c-28ab6cdf395a)
4. Prevent org member checks when an outside contributor creates a pull request that executes the initial pr sync process.
![image](https://github.com/KinsonDigital/Infrastructure/assets/85414302/2ea26aa3-ba14-4f7b-b33d-30cd853b2920)

### Acceptance Criteria

**This issue is finished when:**

- [x] Re-usable workflow created for the initial and manual sync process
- [x] The workflow correctly fails when a non-org user tries to use the `[run-sync]` command.
- [x] Console warning adjusted when issue numbers are not found
- [x] Org member checks not enforced when initial PR syncs are executed
- [x] The workflow _**sync-issue-to-pr.yml**_ is renamed to _**sync-pr-to-issue.yml**_

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
