### ISSUE TITLE
🚧Improve resolve project file workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#167]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the _**resolve-csharp-proj-file.yml**_ workflow by moving the PowerShell code out into a Deno script in the `resolve_project_file_path` job.  This will not only make it easier to update in the future if need be but also make it more stable due to the better features of typescript and Deno.

The inputs going into the Deno script should be the base directory path coming from the workflow `base-path` input.  

> **Note**
> Do not get too crazy with features.  Just take in the input, verify the input, find all **_csproj_** files starting at the base directory path and recursively through the directories, then extract the full file paths where the file name without the extension matches the incoming project name.

> **Note**
> Make sure to set the output with the name `project-file-path`.  This can be seen in the `resolve-file-path` step in the `resolve_proj_file_path` job shown below.  Also, make sure to log the name of the output and its value to the console as a `::notice::`.

**Output Set In Powershell:**
https://github.com/KinsonDigital/Infrastructure/blob/0595c758adaa59d9fd39e48d836923978a3e58e2/.github/workflows/resolve-csharp-proj-file.yml#L67-L70

> **Warning**
> These changes should not effect any other workflows or organization repos that directly or indirectly use this workflow.  Though on the surface it looks like there will be no breaking changes, there is a chance that there will be.

### Acceptance Criteria

**This issue is finished when:**
- [x] Script created to replace resolve csproj powershell code
- [x] _**resolve-csharp-proj-file.yml**_ workflow updated
- [x] Output printed to the console as a `::notice::`

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
