### ISSUE TITLE
🚧Improve build and tests workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#168]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the _**build-csharp-project.yml**_ and _**run-csharp-tests.yml**_ workflows by adding 3 additional workflow inputs so that consumers of these workflows can customize what is being checked out.

Here are the 3 workflow inputs to add:
1. `checkout-ref` - Optional - Default Empty
    - This will get routed to the checkout action `ref` input in the `build_project` job.
2. `checkout-repo` - Optional - Default Empty
    - This will get routed to the checkout action `repository` input in the `build_project` job.
3. ~`custom-checkout` - Optional - Default False~
    - ~This will be used to decide between 2 different check steps to execute.  One step is for when `custom-checkout` is `true` and one for `false`.~

The `checkout-ref` and `checkout-repo` both need to be validated that they are not null if the `custom-checkout` input is set to `true`

### Acceptance Criteria

**This issue is finished when:**
- [x] _**build-csharp-project.yml**_ workflow updated
    - [x] The inputs `checkout-ref` and `checkout-repo` added to the workflow
    - [x] ~Validation added for the `checkout-ref`, `checkout-repo` inputs~
- [x] _**run-csharp-tests.yml**_ workflow updated
    - [x] The inputs `checkout-ref` and `checkout-repo` added to the workflow
    - [x] ~Validation added for the `checkout-ref`, `checkout-repo` inputs~

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
after some investigation during implementation, it was discovered that I don't have to create the `custom-checkout` input.  Instead we will use default values from the `github` context.
