### ISSUE TITLE
🚧Add sync ignore branches feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#170]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to the **_SyncPRToIssue_** process where pull requests with a head branch can be ignored if they exist in an ignore list.  This ignore list should be a comma delimited list of values from an ORG or REPO variable.

The name of the ORG/REPO variable should be _**PR_SYNC_BRANCH_BLACK_LIST**_.
Any branch names in this list will be ignored if the pull request has a head branch that matches any of the branch names.

### Acceptance Criteriacomma-delimited

**This issue is finished when:**
- [ ] _**PR_SYNC_BRANCH_BLACK_LIST**_ org variable added
- [ ] `SyncPRToIssueRunner` updated to skip syncing if the head branch matches any branches in the black list.
    - [ ] Notice printed to GitHub console if skipped due to a black-list match.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
