### ISSUE TITLE
🚧Improve prepare release process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#172]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability for the prepare release process to be used for deno projects.

One of the deno projects that would benefit this is the _**kd_clients**_ project.

Currently, the prepare release process can only be used for dotnet projects.  The reason for this is due to how the dotnet version is pulled.  It pulls the version from the _**csproj**_ file.  Because deno projects don't have this file, an attempt is made to pull the version from a **_csproj_** file that does not exist.

### **Solution**
The solution is to create another repo variable named `PROJECT_TYPE`.  This variable will hold the value of `dotnet` or `deno`.  This variable will then be used in the **_PrepareReleaseRunner.ts_** script.  If the project is a **dotnet** project, the `CSharpVersionService` will be used to pull the version. If it is a **deno** project, then a new service will used to pull the version.

Create a new service class named `DenoVersionService` that will be used for this purpose.

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] New service named `DenoVersionService` created to pull version from _**deno.json**_ files
- [x] The `PrepareReleaseRunner` class updated to use the new variable and service
- [x] The `PROJECT_TYPE` var value is lowercased and trimmed
- [x] The `PROJECT_TYPE` value is checked for valid values and failes/throws error if not correct
- [x] The `PROJECT_TYPE` repo variable is setup for the org with a value of `dotnet`
- [x] Prepare release workflow and process tested on infrastructure
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
