### ISSUE TITLE
🚧Update all workflow deno actions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#174]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all of the deno setup actions in all of the workflows to use a repository variable named `DENO_VERSION`.

```diff
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
-          deno-version: v1.x
+          deno-version: ${{  vars.DENO_VERSION }}
```

### Acceptance Criteria

- [x] All workflows updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
