### ISSUE TITLE
🚧Fix proj resolve issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#178]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with the previous release where the other reusable workflows that utilize the _**resolve-csharp-proj-file.yml**_ workflow was improved with deno scripts.

A required secret was added to the _**resolve-csharp-proj-file.yml**_ workflow, but the secret was not used and added to the other workflows that use it.

Update the other workflows that use the _**resolve-csharp-proj-file.yml**_ workflow to send in a secret.  These workflows will need to also have a required secret input added to them.

> **Warning**
> This is going to be a breaking change to all of the org projects.

### Acceptance Criteria

- [ ] All workflows that use the _**resolve-csharp-proj-file.yml**_ workflow updated to have a required secret and send to the the resolve workflow

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
