### ISSUE TITLE
🚧Fix resolve csharp issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#180]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with an empty `base-path` not to be resolved to the default value of the base repo dir path.

This problem occurs in the _**resolve-csharp-proj-file.yml**_ workflow.  In the PowerShell, check if the `base-path` is empty, use the `${{ github.workspace }}` as the value.

### Acceptance Criteria

- [x] The `base-path` value set to base repository directory path if incoming workflow input is empty.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
