### ISSUE TITLE
🚧Add dotnet SDK checks to release workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#185]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a deno script that checks the version of dotnet for all dotnet projects and compares it to the projects `NET_SDK_VERSION` repository variable value.  If the values do not match, the script will end in a failure with the proper GitHub error message.

This script will then be used in a status check.

### **Behavior to add:**
**Deno Script:**
- The script will be named `validate-sdk-setup` and will have an associated script runner performing the work.
    - This will find each project file that exists in the code base
    - The project will be checked for a repository variable and fail if the variable does not exist
    - Each csharp project found will be checked for a `<TargetFramework>net7.0</TargetFramework>` XML tag
    - The framework value will be processed and compared to the repository variable.
    - The framework value will take precedence when compared to the repo variable when it comes to comparisons of the major, minor, and patch sections of the version.
        > **Note**
        > This means that if the framework value is `net7.0` and the repo variable is `7.0.300`, the script will not fail because the framework value was not `7.0.300`.
    - All project files will be checked and if all of the project framework values are not the same, the script will fail with a descriptive message.
    - When reading the repo variable, it can be prefixed with the letter _**v**_
    - When reading framework value, it must be prefixed with the word 'net'.  This is not a standard version number but a dotnet-specific moniker.
- This script will be executed by a reusable workflow that in turn will be used by the release-related workflows.

### **Workflows:**
- The release workflows to update will be the _**dotnet-action-release.yml**_ and _**dotnet-lib-release.yml**_ workflows.
> [!NOTE]
> For both workflows, add a new job between the `validate_branch` and `validate_versions` jobs named `validate_sdk_setup`.  This job is what will execute the reusable workflow

**Purpose:**
When updating a project to a new dotnet version, will help prevent a release from being performed with any projects set to a dotnet sdk version that does not match the repository variable.  This way maintainers and contributors will not get build and status check failures when contributing due to accidentally forgetting to update the repository variable or one of the projects to the correct dotnet version.

### Acceptance Criteria

```[tasklist]
### Deno Script
- [x] Each project file is loaded and checked
- [x] Script fails and message is displayed if repo variable does not exist
- [x] All projects must have the same framework value
- [x] Message is displayed if all the projects do not have the same value
- [x] The framework and repo variable values are compared
- [x] The csproj framework value takes precedence with the version over the repo variable
- [x] Script fails and error message shown if any of the project framework values do not match the repo variable
- [x] Repo variable starting with the letter 'v' is acceptable.
- [x] Reusable status check workflow created for other projects to use.
```

```[tasklist]
### Workflows
- [x] The _**dotnet-action-relrease.yml**_ workflow updated with a new job to check the SDK setup
- [x] The _**dotnet-lib-relrease.yml**_ workflow updated with a new job to check SDK setup
- [ ] Both jobs are named `validate_sdk_setup`
```

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
