### ISSUE TITLE
🚧Create release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#201]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a release workflow to perform production and preview releases.

The release workflow should do the following:

1. Validates workflow inputs
2. Validates the version workflow input
    > **Note**
    > Use the same concept as the _**kd-cli**_ project by using the _**version-checker.ts**_ script from the project
4. Check that the GitHub release does not exist
    > **Note**
    > Use the _**validate-github-release.yml**_ reusable workflow
6. Run a build status check
7. Run a test status check
8. Run a lint status check
9. Update all of the reusable workflow versions
    > **Note**
    > This will require a commit to be created after updating the versions
11. Run a workflow version status check
> **Note**
> This is to confirm that the update workflow versions have been successful
12. Automatically create the tag (Note: This is the release)
13. Close the milestone
    > **Note**
    > Refer to the `Close Milestone` step in the _**dotnet-lib-release.yml**_ workflow in Infrastructure
14. Repo variables setup for preview vs production releases

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Workflow inputs validated
- [x] Validated that a GitHub release does not exist of the same version
- [x] Build status check executed
- [x] Lint status check executed
- [x] Workflow version status check executed
- [x] Closes milestone upon release
- [x] PREV_PREP_RELEASE_BASE_BRANCH deleted to use org level variable instead
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
