### ISSUE TITLE
🚧Update kd_clients library for bug fix

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#204]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**kd_clients**_ library to version _**v1.0.0-preview.8**_ to inherit bug fix.

### Acceptance Criteria

- [ ] kd_clients library updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Issue Dependencies

- KinsonDigital/kd_clients#35

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
