### ISSUE TITLE
🚧Improve release tweets to work with deno projects

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#205]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the release tweet process to work with deno projects.

Currently, the release tweet template is expected to deal with dotnet releases and releases to nuget.org.
This means the release tweet template contains a link to the nuget release via a URL.  Deno projects of course do not use nuget and need a different URL.

The `SendReleaseTweetRunner` class uses the `ReleaseTweetBuilder` to build the release tweet.  Update the `ReleaseTweetBuilder` to build a release tweet depending on if it is a dotnet project or a deno project.  Use the `PROJECT_TYPE` repo/org variable value to detect what kind of project it is.

Rename the _**release-tweet-template.txt**_ file to _**dotnet-lib-release-tweet-template.txt**_.

Create a new release tweet template with the name _**deno-release-tweet-template.txt**_.  This template will be the same as the dotnet template except instead of a `{NUGET_VERSION}` value for the Nuget Package URL, it will have a deno module URL instead that uses the already existing `{VERSION}` injection value.

### Acceptance Criteria

- [ ] Original release tweet template renamed to signify a dotnet template
- [ ] New release tweet template created for deno projects
- [ ] `ReleaseTweetBuilder` updated for deno releases

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
