### ISSUE TITLE
🚧Add validation scripts

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#21]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add validation scripts for validating versions and release notes.

### Acceptance Criteria

**This issue is finished when:**
- [x] validate tag script added to repo
- [x] validate release notes script added to repo

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
