### ISSUE TITLE
🚧Remove all code related to printing out arg values

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#213]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through all code related to printing out values of the script arguments.  This will involve refactoring all of the cicd scripts from use args to environment variables.  This means that the PowerShell code printed in the GitHub console will not show any arguments being passed into the deno scripts.  

Another benefit of this is that we do not have to worry about accidentally sending a secret into the wrong argument, which the deno scripts happen to print out to the console.  This lowers the chance of leaking secrets to the console.

Remove from the following:
1. Remove from workflows
2. Remove from `ScriptRunner`
3. Remove from scripts that do not use runners

> [!NOTE]
> Search the entire code base where `Deno.args` are used to help find areas where args are being printed.
> A risk could be refactoring code in the future and accidentally positioning arguments incorrectly, which would accidentally expose the tokens and secrets.  This is especially true with the tweet side of infrastructure.

### **Reason**
This reduces security issues that can occur in the future.  This will also reduce maintenance.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Arg printing removed from workflows
- [x] Arg printing removed from `ScriptRunner`
- [x] Arg printing removed from script files that do not use the `ScriptRunner` class
- [x] Codebase wide search for `Deno.args` done.
```

```[tasklist]
### Workflows and scripts
- [x] `add-item-to-project.yml` workflow and associated script has been updated
- [x] `build-status-check.yml` workflow and associated script has been updated
- [x] `dotnet-lib-release.yml` workflow and associated script has been updated
- [x] `nuget-package-does-not-exist.yml` workflow and associated script has been updated
- [x] `resolve-csharp-proj-file.yml` workflow and associated script has been updated
- [x] `validate-csharp-version.yml` workflow and associated script has been updated
- [x] `validate-github-release.yml` workflow and associated script has been updated
- [x] `validate-milestone-status.yml` workflow and associated script has been updated
- [x] `validate-sdk-setup.yml` workflow and associated script has been updated
- [x] `validate-tag.yml` workflow and associated script has been updated
- [x] `workflow-version-status-check.yml` workflow and associated script has been updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
The prepare release and sync bot related scripts were not updated due to them being removed in the future.

The prepare release script is replaced by the kd-admin tool and the syncing scripts will eventually be replaced by the new syncing system
