### ISSUE TITLE
🚧Fix issue with building tweet

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#214]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with building a tweet during the release process.  This is occurring due to some bad logic in the `ReleaseTweetBuilder` file.

Reference to code below:
https://github.com/KinsonDigital/Infrastructure/blob/a6b0253c95d41a6272938f59269e881a8e6a111d/cicd/core/ReleaseTweetBuilder.ts#L53-L56

> [!important]
> Make sure to heavily test the `ReleaseTweetBuilder` and `SendReleaseTweetRunner` classes.  Looking at the logic and change history of the `ReleaseTweetBuilder` class, successful tweets have gone out with the current logic and the reason of how is unknown.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Issue fixed with building release tweet
- [x] ReleaseTweetBuilder heavily tested
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
