### ISSUE TITLE
🚧Add repo variable trimming

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Infrastructure#218]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Trim line return characters from the end of the `CICD_SCRIPTS_VERSION`  repo variable. 
Make sure to trim `\r` and `\n` from the end of the variable. 
This change needs to be introduced into the _**resolve-csharp-proj-file.yml**_ workflow in the `resolve_proj_file_path`  job, and `Create Script URL` step. 

**Reason**
Jobs are failing due to extra line return chars existing at the end repo variable.  

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Repo variable trimming added to URL construction process
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
