### ISSUE TITLE
🚧Remove prepare release process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#221]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the prepare release process.  ~This is going to be turned into a CLI tool.~

This has been turned into a CLI tool, the [kd-admin](https://github.com/KinsonDigital/kd-admin) project.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] The `PrepareReleaseRunner` scripts has been removed
- [x] The `prepare-release.ts` file has been removed
- [x] The `prepare-release.yml` workflow file has been removed
- [x] The `Prepare Release` launch config has been removed
- [x] The `prepareReleaseExecutor` import in the _**mod.ts**_ file has been removed
```

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
