### ISSUE TITLE
🚧Change github release step

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#222]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the GitHub release process by swapping out the `softprops/action-gh-release@v1` GitHub action with the GitHub CLI tool.

The following workflows need to be updated:

1. _**dotnet-action-release.yml**_
2. _**dotnet-lib-release.yml**_

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] The GitHub release step has been replaced with the GitHub CLI tool for the _**dotnet-action-release.yml**_ workflow
- [x] The GitHub release step has been replaced with the GitHub CLI tool _**dotnet-lib-release.yml**_ workflow
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
