### ISSUE TITLE
🚧Fix issue with pr description during initial sync

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#226]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When an issue is initially synced to a pull request, the note added to the PR description is in the old style. It needs to be updated to the new style.

The specific fix can be found in the `PRTemplateManager.ts` file on line 160.  

> [!Note]
> Remove the `\t` character from the beginning.  Unfortunately, the new style of admonitions does not support tabbing.

> [!Note]
> Extra work would be to replace the _**ToDo Items**_ section with a new task list like in the _**Acceptance Criteria**_ section and to fix any grammar or spelling to match the org level project item issue template.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] PR template creatation fixed
- [x] Project item issue template updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
