### ISSUE TITLE
🚧Create CICD scripts for org

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#23]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create various CICD scripts for the organization using deno.

The scripts to create are:
1. Create a script that validates if a milestone exists
2. Create a script that validates if all of the issues in the milestone exist in the release notes
3. Create a script that will auto-label a PR if the head branch is a **preview** branch
4. Create a script that auto-adds a PR to a project
5. Create a script that closes a milestone

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] A script created that validates if a milestone exists
- [x] A script created that will auto-label a PR if the head branch is a **preview** branch
- [x] A script created that validates if all of the issues in the milestone exist in the release notes
- [x] A script created that validates that all issues and prs in a milestone are closed and not in draft
- [x] A script created that auto-adds a PR to a project
- [x] A script created that auto-adds an issue to a project
- [x] A script created that closes a milestone
```

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
