### ISSUE TITLE
🚧Update dotnet lib release to include debug symbols

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#233]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**dotnet-lib-release.yml**_ workflow to include the debug symbols in the Nuget package.

This will involve updating the `Create Nuget Package` steps and `Publish Nuget Package`.

Refer to the [ms docs](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) for info on the commands.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking-changes` |
| New Feature         | `✨new-feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low-priority`    |
| Medium Priority     | `medium-priority` |
| High Priority       | `high-priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
