### ISSUE TITLE
🚧Improve step names

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#234]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Look through all steps for all workflows where the version being used for the step action could be used in the name.  

**Example**
This:
```yml
- name: Set Up Deno
  uses: denoland/setup-deno@v1
  with:
    deno-version: ${{ vars.DENO_VERSION }}
```

Should become:
```yml
- name: Set Up Deno (${{ vars.DENO_VERSION }})
  uses: denoland/setup-deno@v1
  with:
    deno-version: ${{ vars.DENO_VERSION }}
```

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [ ] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [ ] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking-changes` |
| New Feature         | `✨new-feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low-priority`    |
| Medium Priority     | `medium-priority` |
| High Priority       | `high-priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes.  The work was completed with a previous issue.
