### ISSUE TITLE
🚧Improve dotnet lib release workflow validation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#236]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Improve the validation logic in the dotnet lib release reusable workflow by combining all of the logic across all jobs into a single job where each step will perform the validation.
Each step will run without failing the workflow and the last step will process all of the steps and print the results and fail the workflow if any step has failed.

This will simplify the workflow, improve performance, and catch all issues with a single job instead of skipping further validation jobs because previous ones failed.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The _**dotnet-lib-release.yml**_ workflow has been updated
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking-changes` |
| New Feature         | `✨new-feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low-priority`    |
| Medium Priority     | `medium-priority` |
| High Priority       | `high-priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
