### ISSUE TITLE
🚧Fix env vars in dotnet release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#243]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Fix the environment variables 'BASE_SEARCH_DIR_PATHL' and 'NET_SDK_VERSIONL' in the `Validate SDK Versions` step in the `run_prerelease_validation` job in the _**dotnet-lib-release.yml**_ workflow.

These environment variables are misnamed and contain an extra `L` at the end of the var names.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The environment variable `BASE_SEARCH_DIR_PATHL` has been renamed.
- [x] The environment variable `NET_SDK_VERSIONL` has been renamed.
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking-changes` |
| New Feature         | `✨new-feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low-priority`    |
| Medium Priority     | `medium-priority` |
| High Priority       | `high-priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
