### ISSUE TITLE
🚧Create twitter announcement script

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#27]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a script that pushes a tweet for release announcements.  This will require creating a `TwitterClient` class.

**OAuth References:**
1. Refer to [here](https://pandeysoni.medium.com/how-to-create-oauth-1-0a-signature-in-node-js-7d477dead170) for information on how to implement the **OAuth v1.0** side of things.
2. [Twitter Docs (OAuth Signature)](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/creating-a-signature)
3. [Akana](https://help.akana.com/content/current/cm/api_oauth/aaref/Ref_OAuth_AuthorizationHeader_10a.htm)

### Acceptance Criteria

**This issue is finished when:**
- [x] Tweet script is created
- [x] The discord ID is added to the org as a variable for consumption by the CICD system.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
