### ISSUE TITLE
🚧Remove script description code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#29]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Disable all description class usage in each of the scripts.  This currently needs to change due to needing to pull the descriptions over HTTP instead of local file paths.  We are not in a position right now to implement it. This can be done at a later time.

Just remove the use of the class for now so we can keep moving forward.

### Acceptance Criteria

**This issue is finished when:**
- [ ] `ScriptDescription` usage removed from each script file

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
