### ISSUE TITLE
🚧Create NuGet pkg check script

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#32]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a deno script that checks if a NuGet package exists of a particular version.
The script will pull **ALL** versions.  If there is a 404 something simular is returned, throw an exception that the NuGet package does not exist.  If it does, use the list of versions to check if the incoming version exists.

Create  NuGet HTTP client class to do NuGet operations.  This will be used in the script.  The name of the script file should be _**nuget-pkg-exists.ts**_.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Create script file named _**nuget-pkg-exists.ts**_
- [ ] Create NuGet client class named _**NuGetClient.ts**_

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
