### ISSUE TITLE
🚧Fix arg processing with release notes script

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Infrastructure#41]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where the arguments coming into the _**release-notes-exist.ts**_ script are not properly being processed.

Remove the casing forcing logic, to be not case sensitive so the notes can be properly checked.

### Acceptance Criteria

**This issue is finished when:**
- [x] The arg processing for the release type is corrected

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
