### ISSUE TITLE
🚧Create cicd scripts for pr syncing

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#49]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create all of the necessary CICD deno scripts to allow the foundation of creating a workflow bot that can be used for syncing an issue's setup to a pull request. This will be a major time saver in the future.

The things to sync should be the following:
1. The title
2. The assignees
3. The labels
4. The org project
5. The milestone

This script should be named _**sync-issue-to-pr.ts**_.  This script will have all of the proper validation of the arguments coming into the script as well as validating if the arguments are valid in the GitHub system such as the pr number and default reviewer.

### Acceptance Criteria

**This issue is finished when:**
- [x] The things to sync should be the following:
    - [x] The title
    - [x] The assignees
    - [x] The labels
    - [x] The org project
    - [x] The milestone

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
test from issue

**Comment by CalvinWilkinson** [comment]
comment from ISSUE

**Comment by CalvinWilkinson** [comment]
comment from issue

**Comment by CalvinWilkinson** [comment]
comment from issue

**Comment by CalvinWilkinson** [comment]
comment from issue

**Comment by CalvinWilkinson** [comment]
comment from issue

**Comment by CalvinWilkinson** [comment]
[run-sync]

**Comment by CalvinWilkinson** [comment]
asdf
