### ISSUE TITLE
🚧Create script to easily set up release

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#59]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a script to quickly set up a release.  This will entail the following in the order shown below:

1. Creates a `release` branch from master
    > **Note** Prod vs Preview
    > If production, create the `release` branch from master
    > If preview, create the `release` branch from the preview branch.
3. Creates an empty commit
4. Updates the version in the csproj file and create a commit of the change
5. Creates a new set of preview or prod release notes from a template.
    > **Note** This will pull all of the issues and pull requests from a milestone and use them to generate the release notes
    > - The release note line item will be a combination of a markdown link to the issue or pr and the title of the issue or pr.
    > - The release note line items will be put into the correct section of the release notes
    > - Create a release note generator class that will take in a list of issues and pull requests as input and will be used to generate the notes.
7. Creates a pull request to merge the release branch
    > **Note** Prod vs Preview
    > If prod, will create a PR that merges the release branch into `master`
    > If prev, will create a PR that merges the release branch into `preview`

At this point, all that is needed to be done is to update the release notes and it is ready to be reviewed and merged.

### **Purpose:**
The purpose of this is to save time by making it easy to create everything required to do a release.  Instead of doing all this manually every time a release needs to be done, this can be used instead.  This script will be executed from a single workflow called _**setup-release.yml**_.  This workflow will be manually executed from the actions page and be used for setting up both prod and preview releases.

The workflows will have the following inputs:
1. Release type
2. Release version

> **Note** First things to consider:
> This will only work if we can use the REST and/or GraphQL APIs to easily create the branches and commits that we need, as well as create a pull request.

### Acceptance Criteria

**This issue is finished when:**
- [x] Class created to easily generate release notes
- [x] Ability added to create a remote branch
- [x] Ability added to create a pull request
- [x] Release notes are auto-generated
    - [x] A link is created to the issue or PR
    - [x] The description of the markdown line item will be the title of the issue or PR
    - [x] The item will be put into particular sections based on the labels they contain.
- [x] Create a script that can create a prod or preview release
    - [x] Creates a prod release
        - [x] Creates a pr that merges a release branch into another branch
        - [x] Creates prod release notes
    - [x] Creates a preview release
        - [x] Creates a pr that merges a release branch into another branch
        - [x] Creates preview release notes
- [x] Create a reusable workflow to set up a release
    - [x] Is named _**prepare-release.yml**_
    - [x] Takes in a project name
    - [x] Takes in release type input
    - [x] Takes in a version string input
    - [x] Validates the project name, release type version string inputs
- [ ] Re-enable workflows
- [ ] All script versions pointing to a new version which is _**v9.0.0**_

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
