### ISSUE TITLE
🚧Create new command to add sync template to a pr

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#62]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a new feature by adding a new command to the sync process to add the pr template to a pull request.   This will completely replace the PR description with the template.

Use the command `[add-pr-template]`.  Using this in a comment will add the template to the PR.

### Acceptance Criteria

**This issue is finished when:**
- [ ] New command added to the sync system.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
@CalvinWilkinson is this still necessary?

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson is this still necessary?

It is a not "necessary".  If the syncing system is working fine, then it is useless.  But if the sync system has issues, this can help make it easier to just add it "manually" instead of relying on the auto-sync workflow to work without issues and to also trigger.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
The syncing feature is being removed.
