### ISSUE TITLE
🚧Add improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#63]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where the PR template file cannot be found.

The issue is that the repo used to find the template is the same repo name that is being injected into the script via the arguments.  This repo name is currently the name of the repo that the script is running **FOR**.  But the repo does not contain the template file. 

Example: CASL does not contain the file but that is the repo name being used when trying to download the template for use.   The repo should always be named infrastructure.

To solve this without having to create even more arguments for the scripts, create a **VariableClient** class that has the ability to get and manage organization variables.  Make sure to add code docs to the client that talk about which kind of token permission is required for this to work.  This can be found in the API docs.

The idea here is to search for an org repo variable that contains the value needed and that can be used.  If the variable is not found, print a console message that the org variable and value are required for the script to do its job.

Do this same process for all repo-level variables, this way we do not have to send them into the scripts anymore.  Refactor each script to remove the org level values if they exist and update the workflows.

### Acceptance Criteria

**This issue is finished when:**
- [x] ~Org variable client created~
- [x] Org and repo variable functions added to `OrgClient` and `RepoClient` classes.
- [x] All scripts that use a repo-level value as an arg, are removed.
- [x] All scripts that require repo-level scripts are refactored to reach out for the values themselves.
    - [x] Each script checks if the repo vars exist and if not, prints an error message if they do not.
- [x] All workflows updated to reflect arg changes related to repo-level variables.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
