### ISSUE TITLE
🚧Fix sync template issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#65]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where the PR template file cannot be found.

The issue is that the repo used to find the template is the same repo name that is being injected into the script via the arguments.  This repo name is currently the name of the repo that the script is running **FOR**.  But the repo does not contain the template file. 

Example: CASL does not contain the file but that is the repo name being used when trying to download the template for use.   The repo should always be named infrastructure.

### Acceptance Criteria

**This issue is finished when:**
- [x] Issue fixed with sync template

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
