### ISSUE TITLE
🚧Remove reviewer as status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#69]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the default reviewer is used as part of the status check process to prevent a pr from being merged.  This is not required due to this functionality already existing in the GitHub ecosystem.  Remove the status check requirements from the syncing process.

**Extra:**
Add an `if` to the job in the _**sync-issue-to-pr.yml**_ workflow that will only run the job if the head branch is a feature branch

### Acceptance Criteria

**This issue is finished when:**
- [x] The default reviewer used as a status check is removed
- [x] if logic added to job

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
