### ISSUE TITLE
🚧Simple improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#70]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Improvement 1
Update the name of the step from **Validate Release Notes** to **Validate Release Notes Exist** in the job responsible for validating release notes.

This change is located in the **validate-release-notes.yml** file > `validate_release_notes` job > 3rd step.

```yml
- name: Validate Release Notes 👈🏻 This step name here needs to be changed
  run: |
    $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/release-notes-exist.ts";
  
    <# Deno Args:
      1. ReleaseType
      2. Version
    #>
    deno run `
      --allow-read `
      "$scriptUrl" `
      "preview" `
      "${{ inputs.version }}";
```

### Improvement 2

Insert a missing arg item in the multi-line PowerShell comment between item **_3_** and item **_4_** with the name `Ignore Label List`.  This is simply missing arg docs for the script below it.
This change exists in the last step named `Validate Release Notes` in the `validate_release_notes` job in the _**validate-release-notes.yml**_ file.

```diff
      - name: Validate Release Notes
        run: |
          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-release-notes.ts";
        
          <# Deno Args:
            1. RepoName
            2. ReleaseType
            3. Version
+            4. Ignore Label List - Comma delimited values
-            4. PRLabel
+            5. PRLabel
-            5. GitHubToken
+            6. GitHubToken
          #>
          deno run `
            --allow-read --allow-net `
            "$scriptUrl" `
            "${{ inputs.project-name }}" `
            "preview" `
            "${{ inputs.version }}" `
            "🚀Preview Release" `
            "${{ inputs.pr-label }}" `
            "${{ secrets.cicd-rest-api }}";
```

## Acceptance Criteria

**This issue is finished when:**
- [x] Step renamed to be more clear on its purpose
- [x] powershell docs updated

## ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
