### ISSUE TITLE
🚧Fix step if logic for dry runs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#75]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the if logic used for various steps in the `perform_release` job in the _**release.yml**_ workflow.

Currently, the if logic is comparing for string values but should be comparing for boolean values.

The syntax is `${{ inputs.dry-run == 'false' }}` and should be `${{ inputs.dry-run == false }}`

Every instance of this should be fixed.

### Acceptance Criteria

**This issue is finished when:**
- [x] step if logic fixed for dry runs

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
