### ISSUE TITLE
🚧Change how repo name is used with clients

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#77]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Change how the repo name is setup when working with all of the GitHub clients.

Most of the functions take in a `repoName` parameter.  Instead of the functions using this parameter, set this up to be used in the constructor instead.  This way it does not need to be used for every single function.

Also. do the same for the organization/repoowner value as well. Instead of the `protected` `this.organization` field in the `GitHubClient` class being named `organization`, rename this to be `owner`.

Also, add new properties to the abstract `GitHubClient` client for the repo and organization/owner values.  These properties will be read only.

### Acceptance Criteria

**This issue is finished when:**
- [ ] `GitHubClient` refactored to have the constructor take in owner and repo names
- [ ] Read only props added to the `GitHubClient` to expose the repo owner and name values
- [ ] All parameters for all client functions that have a repo name as a parameter are removed
- [ ] All scripts refactored to adjust for client function param changes.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
