### ISSUE TITLE
🚧Create transpile readme script

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#78]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a custom script that can be used to transpile HTML content into markdown content.  This will be used to transpile the HTML that is embedded into the project README files so that way they can be prepared for Nuget packages. 

**Reason:**
The HTML is great for setting up the readme for GitHub but HTML is not recognized in the Nuget ecosystem.  Because of this, the HTML looks like text instead of being rendered when viewing the readme in nuget.org.  To fix this, the HTML has to be transpiled into markdown.

The release workflow also needs to have an additional step that will be used to perform the transpiling of the readme file.  This step needs to occur right before the creation of the NuGet package.

### Acceptance Criteria

**This issue is finished when:**
- [x] README transpile script created
- [x] Step added to release job in _**release.yml**_ file to transpile the readme file
    - [x] Runs right before the NuGet package creation process.
    - [x] Add `bool` workflow input that is used to turn off and on the transpilation process
        > **Note** Default will be `false` and the step will only run if it is true

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
