### ISSUE TITLE
🚧Create reusable release workflow for github actions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#80]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a release reusable workflow for releasing GitHub actions that are built using dotnet.

The name of this workflow should be _**dotnet-action-release.yml**_.  This signifies that the release is only good for GitHub actions that are built using dotnet.  Actions built with other tech stacks would have different requirements.

> **Note** Make sure to NOT validate the release notes.  GitHub Actions will no longer have milestones. 

Use the _**release.yml**_ workflow in the [VersionMiner](https://github.com/KinsonDigital/VersionMiner/blob/master/.github/workflows/release.yml) project as a guide to how the workflow should work.  
> **Warning** The workflow will not be the same.  It is just a guide.  It will have to be refactored to take various inputs into the new workflow and those inputs will be used throughout the new workflow which will make it reusable.
> Refer to this [Infrastructure Release Workflow](https://github.com/KinsonDigital/Infrastructure/blob/master/.github/workflows/release.yml) as a guide on the reusable side of the implementation.

Below are some examples of things that need to be set up as workflow input:
1. The branch that the workflow is running on in the first step
2. The type of release which will be a value of `Preview` or `Production`
    > **Note:** This needs to be validated in a step early in the job

Below are some examples of things that should become a repo variable:
1. The name of the project which would be used in the construction of the project file path in the **Build Main Project** and **Run Unit Tests** steps
2. The relative directory path to the release notes
    > **Note** Reference the [CASL Repo Variables](https://github.com/KinsonDigital/CASL/settings/variables/actions) on variable names and values.

I will not list them all here.  These need to be figured out one at a time until the workflow is as reusable as possible.  The key to this is the combination of repo variables and workflow inputs.  Those 2 things together will make it reusable.

### Acceptance Criteria

**This issue is finished when:**
- [x] Reusable release workflow created for dotnet GitHub actions
- [x] Workflow named to _**dotnet-action-release.yml**_
- [x] Any references to the `CICD_TOKEN` changed to use a workflow input instead

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
