### ISSUE TITLE
🚧Refactor for prod releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#82]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor/improve the release workflow to be able to be used for production OR preview releases.

Update the **_validate-csharp-version.yml_** and _**validate-tag.yml**_ workflows to be able to take in another input that dictates the type of version to validate.  This will be either a production or preview-type version.

This will require the following:
1. The `validate_version` step will need to call a newer version of the _**validate-csharp-version.yml**_ workflow which will take in another input which is the version type.
2. The `validate_tag` step will need to call a newer version of the _**validate-tag.yml**_ workflow which will take in another input which is the version type.
3. Fix the `validate_tag` display name
4. Refactor the _**release-notes-exists.ts**_ script to pull in repo variables to build the notes path.
    > **Note** This is going to require updates to the _**validate-release-notes.yml**_ workflow
5. Add a new workflow input that is the type of release
    > **Note** Add validation for this new input in the _**validate_workflow_inputs**_ job.
7. Update the _**Preview Release**_ step in the `perform_release` job to release as a preview or prod depending on a new release type workflow input
8. Look in all of the scripts and refactor them to use repo variables where possible

### Acceptance Criteria

- [x] Look in all of the scripts and refactor them to use repo variables where possible
    > **Note** Make sure to update all related workflows that use the scripts
- [x] New workflow input named **release-type** added
  > **Note** Add validation for this new input in the _**validate_workflow_inputs**_ job.
- [x] The `validate_version` step calls a newer version of the _**validate-csharp-version.yml**_ workflow
- [x] The `validate_tag` step calls a newer version of the _**validate-tag.yml**_ workflow
- [x] The `validate_tag` job display name fixed
- [x] The _**Preview Release**_ step in the `perform_release` job setup for both prod and prev releases
- [x] Update all script versions to the latest version

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
