### ISSUE TITLE
🚧Fix issue with unit test workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#9]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the 'run-csharp-tests.yml` unit test workflow has an issue with referencing a previous step for its output value.

The step with the reference issue is the last step named `Execute Unit Tests`.

Currently the reference is `steps.resolve-path.outputs.file-path` and it should be `steps.resolve-file-path.outputs.file-path`.

Fix all references in the workflow.

### Acceptance Criteria

- [x] Job step reference fixed in unit test workflow

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                      |
|---------------------|--------------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Infrastructure/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Infrastructure/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Infrastructure/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Infrastructure/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Infrastructure/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Infrastructure/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Infrastructure/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Infrastructure/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Infrastructure/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
