### ISSUE TITLE
🚧Add sync base branch var support

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Infrastructure#91]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add support for custom base branch requirements for the syncing system.
This will require updating the _**sync-issue-to-pr.ts**_ and _**sync-bot-status-check.ts**_ scripts.

The variable should be set up to be optional and if the variable does not exist, the default base branches _**main**_ and _**preview**_ will be used.

The name of the repo variable should be **PR_SYNC_BASE_BRANCHES**.

The PR template system needs to be updated to inject the name of the branch based on if the repo variable exists and if it contains single or multiple branch names.
1. The injection will only occur on the initial sync
2. The grammar of the pr template will change based on if there is 1 branch or multiple branches.
3. The PR template will reflect the default text below if the optional REPO variable does not exist.
    - The pull request base branch must be a 'main' or 'preview' branch.

### Acceptance Criteria

**This issue is finished when:**
- [x] The _**sync-issue-to-pr.ts**_ script updated
    - [x] Variable set up as optional
- [x] _**sync-bot-status-check.ts**_ script updated
    - [x] Variable set up as optional
- [x] The PR template system is set up to inject the branches.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                     |
|---------------------|---------------------------|
| Bug Fixes           | `🐛bug`                   |
| Breaking Changes    | `🧨breaking changes`      |
| Enhancement         | `enhancement`             |
| Workflow Changes    | `workflow`                |
| Code Doc Changes    | `🗒️documentation code`    |
| Product Doc Changes | `📝documentation product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                    |
|---------------------|--------------------------------------------------------------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
